### ISSUE TITLE
Wrong output path in uuu(-static-link).vcxproj

### ISSUE THREAD

**Issue by keelung-yang** [NXPmicro/mfgtools#214]
Since uuu is an application, not a static or dynamic library, it shouldn't be outputted to a lib/dll directory.
It's better to put it into the same directory as other vc projects in .sln:

![image](https://user-images.githubusercontent.com/20385450/90211893-98aec180-de24-11ea-9d9a-730780eb33ae.png)

![image](https://user-images.githubusercontent.com/20385450/90211815-5eddbb00-de24-11ea-8d33-00ed49b656ca.png)

**Comment by nxpfrankli** [comment]
Yes, But I don't want to change libusb directory, which submodule to libusb git repo. 
So I follow up libusb output directory. 

At beginning, we use dynatmic link because libusb is lgpl license.   If uuu put to other directory, uuu can't be launch by VS because missed libusb.dll. 

After clearfy we can static link libusb, we continue to use this method.

**Comment by keelung-yang** [comment]
uuu can't be launched now without modifying. 
![image](https://user-images.githubusercontent.com/20385450/90214566-82f0ca80-de2b-11ea-946f-2bd473822562.png)
Since uuu.exe in `mfgtools\x64\Debug\dll` and libusb-1.0.dll in `mfgtools\libusb\x64\Debug\dll`

No need to modify libusb, just add a post-build event to uuu project settings, such as
```copy /y "$(SolutionDir)..\libusb\$(Platform)\$(Configuration)\dll\*.dll"  $(Platform)\$(Configuration)\```

**Comment by nxpfrankli** [comment]
I have not touch dynamtic link for long time. Maybe libusb change it

**Comment by keelung-yang** [comment]
What kind of touching as a reason of refusing to fix?
**uuu can't be launched by vs now without modifying**, IS  THAT OK?

**Comment by nxpfrankli** [comment]
fixed patch pushed. System auto close it.
